tasks:
  - init: |
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 23F3D4EA75716059
      sudo apt-add-repository https://cli.github.com/packages
      sudo apt-get update
      sudo apt-get upgrade
      sudo apt-get install libgl-dev gh
      rustup install nightly
      rustup default nightly
      rustup component add rustfmt
      rustup target add wasm32-unknown-unknown wasm32-unknown-emscripten
      cargo install cargo-audit
      cargo fetch
      git submodule update --init
      git submodule foreach git reset --hard
      cd emsdk && ./emsdk install latest && ./emsdk activate latest
      source "/workspace/apollo/emsdk/emsdk_env.sh"
      echo 'source "/workspace/apollo/emsdk/emsdk_env.sh"' >> $HOME/.bash_profile
      echo 'source "/workspace/apollo/emsdk/emsdk_env.sh"' >> $HOME/.zsh_profile
      cargo check
