tasks:
  - init: | 
      rustup install nightly
      rustup default nightly
      rustup component add rustfmt
      cargo fetch
      git submodule update --init
      git submodule foreach git reset --hard
      cd emsdk && ./emsdk install latest && ./emsdk activate latest
      source "/workspace/apollo/emsdk/emsdk_env.sh"
      echo 'source "/workspace/apollo/emsdk/emsdk_env.sh"' >> $HOME/.bash_profile
      cargo check
