name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    strategy:
      matrix:
        toolchain: [nightly]
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: cargo generate-lockfile
      - name: Cache build outputs
        uses: actions/cache@v3
        with:
          path: |
            ~/target
            ~/**/build/
          key: cache-${{ hashFiles('~/Cargo.lock') }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: rustup update nightly
      - run: rustup default nightly
      - run: rustup component add clippy
      - run: cargo check
      - run: cargo clippy
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: rustup update nightly
      - run: rustup default nightly
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
