name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        toolchain: [nightly]
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --verbose
      - name: Build (wasm)
        run: cargo build --verbose --target=wasm32-unknown-unknown
      - name: Run tests
        run: cargo test --verbose
