name: Formatting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: 0 * * * *
  
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: rustup install nightly && rustup default nightly
      - run: cargo fmt --verbose
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4