name: Release Plz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Rust
        run: rustup default nightly
      - name: Install release-plz
        run: cargo install release-plz
      - name: Configure Git
        run: |
          git config --global user.email "release-plz@github.com"
          git config --global user.name "release-plz"
      - name: Run release-plz
        run: |
          release-plz release-pr \
            --git-token ${{ secrets.GITHUB_TOKEN }} \
            --repo-url https://github.com/paperclip-universe/apollo
          release-plz release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
